
import java.awt.List;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author David Thomsen
 */
public class FlooringApplication extends javax.swing.JFrame {

    /**
     * Creates new form FlooringApplication
     */
    public FlooringApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTabbedPane = new javax.swing.JTabbedPane();
        florringPanel = new javax.swing.JPanel();
        floorLengthLabel = new javax.swing.JLabel();
        floorWidthLabel = new javax.swing.JLabel();
        floorLengthTextField = new javax.swing.JTextField();
        floorWidthTextField = new javax.swing.JTextField();
        floorTypeLabel = new javax.swing.JLabel();
        woodRadioButton = new javax.swing.JRadioButton();
        carpetRadioButton = new javax.swing.JRadioButton();
        summaryPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        summaryTextArea = new javax.swing.JTextArea();
        customerPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        addreddLabel = new javax.swing.JLabel();
        customerNameTextField = new javax.swing.JTextField();
        customerAddressTextField = new javax.swing.JTextField();
        calculatePanel = new javax.swing.JPanel();
        floorAreaLabel = new javax.swing.JLabel();
        floorCostLabel = new javax.swing.JLabel();
        floorAreaTextField = new javax.swing.JTextField();
        floorCostTextField = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        orderListButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        orderListTable = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flooring Application");

        floorLengthLabel.setText("Floor Length:");

        floorWidthLabel.setText("Floor Width:");

        floorTypeLabel.setText("Floor Type:");

        buttonGroup.add(woodRadioButton);
        woodRadioButton.setSelected(true);
        woodRadioButton.setText("Wood");

        buttonGroup.add(carpetRadioButton);
        carpetRadioButton.setText("Carpet");

        javax.swing.GroupLayout florringPanelLayout = new javax.swing.GroupLayout(florringPanel);
        florringPanel.setLayout(florringPanelLayout);
        florringPanelLayout.setHorizontalGroup(
            florringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(florringPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(florringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(florringPanelLayout.createSequentialGroup()
                        .addComponent(floorTypeLabel)
                        .addGap(24, 24, 24)
                        .addComponent(woodRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carpetRadioButton))
                    .addGroup(florringPanelLayout.createSequentialGroup()
                        .addComponent(floorWidthLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(floorWidthTextField))
                    .addGroup(florringPanelLayout.createSequentialGroup()
                        .addComponent(floorLengthLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(floorLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        florringPanelLayout.setVerticalGroup(
            florringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(florringPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(florringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floorLengthLabel)
                    .addComponent(floorLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(florringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floorWidthLabel)
                    .addComponent(floorWidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(florringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floorTypeLabel)
                    .addComponent(woodRadioButton)
                    .addComponent(carpetRadioButton))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Flooring", florringPanel);

        summaryTextArea.setEditable(false);
        summaryTextArea.setColumns(20);
        summaryTextArea.setRows(5);
        jScrollPane1.setViewportView(summaryTextArea);

        javax.swing.GroupLayout summaryPanelLayout = new javax.swing.GroupLayout(summaryPanel);
        summaryPanel.setLayout(summaryPanelLayout);
        summaryPanelLayout.setHorizontalGroup(
            summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        summaryPanelLayout.setVerticalGroup(
            summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Summary", summaryPanel);

        welcomeLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        welcomeLabel.setText("Welcome to Flooring Application");

        nameLabel.setText("Customer Name:");

        addreddLabel.setText("Customer Address:");

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addreddLabel)
                            .addComponent(nameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customerNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(customerAddressTextField)))
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(welcomeLabel)
                .addGap(40, 40, 40)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(customerNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addreddLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerAddressTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(199, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Customer", customerPanel);
        customerPanel.getAccessibleContext().setAccessibleName("");

        floorAreaLabel.setText("Floor Area:");

        floorCostLabel.setText("Floor Cost:");

        floorAreaTextField.setEditable(false);

        floorCostTextField.setEditable(false);

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        submitButton.setText("Submit Order");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        orderListButton.setText("Order List");
        orderListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderListButtonActionPerformed(evt);
            }
        });

        orderListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Customer Name", "Customer Address", "Flooring Type", "Floor Area", "Floor Cost"
            }
        ));
        jScrollPane4.setViewportView(orderListTable);

        javax.swing.GroupLayout calculatePanelLayout = new javax.swing.GroupLayout(calculatePanel);
        calculatePanel.setLayout(calculatePanelLayout);
        calculatePanelLayout.setHorizontalGroup(
            calculatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calculatePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(calculatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(calculatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(calculatePanelLayout.createSequentialGroup()
                            .addComponent(floorCostLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(floorCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(calculatePanelLayout.createSequentialGroup()
                            .addComponent(floorAreaLabel)
                            .addGap(88, 88, 88)
                            .addComponent(floorAreaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(calculatePanelLayout.createSequentialGroup()
                        .addComponent(calculateButton)
                        .addGap(47, 47, 47)
                        .addComponent(submitButton)
                        .addGap(53, 53, 53)
                        .addComponent(orderListButton)))
                .addGap(78, 78, 78))
            .addGroup(calculatePanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        calculatePanelLayout.setVerticalGroup(
            calculatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calculatePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(calculatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floorAreaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floorAreaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(calculatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(floorCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floorCostLabel))
                .addGap(18, 18, 18)
                .addGroup(calculatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calculatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(calculateButton)
                        .addComponent(orderListButton))
                    .addComponent(submitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Calculate", calculatePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        double width, length, area, cost, unit;
        try {
            width = Double.parseDouble(floorWidthTextField.getText());
            length = Double.parseDouble(floorLengthTextField.getText());
            area = width * length;
            unit = woodRadioButton.isSelected() ? 20 : 10;
            cost = unit * area;
            floorAreaTextField.setText(area + " ft2");
            floorCostTextField.setText("$" + cost);
        } catch (Exception e) {
            floorAreaTextField.setText("Please enter valid data (width floor and length floor)");
            floorCostTextField.setText(e.toString());
        }
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        StringBuilder sb = new StringBuilder();
        sb.append("Customer Name: ").append(customerNameTextField.getText()).append("\n");
        sb.append("Customer Address: ").append(customerAddressTextField.getText()).append("\n");
        sb.append("Floor Width: ").append(floorWidthTextField.getText()).append("\n");
        sb.append("Floor Length: ").append(floorLengthTextField.getText()).append("\n");
        String type = woodRadioButton.isSelected() ? "Wood" : "Carpet";
        sb.append("Floor Type: ").append(type).append("\n");
        sb.append("Floor Area: ").append(floorAreaTextField.getText()).append("\n");
        sb.append("Floor Cost: ").append(floorCostTextField.getText()).append("\n");
        summaryTextArea.setText(sb.toString());

        double width, length, area, cost, unit;
        cost = 0;
        area = 0;
        try {
            width = Double.parseDouble(floorWidthTextField.getText());
            length = Double.parseDouble(floorLengthTextField.getText());
            area = width * length;
            unit = woodRadioButton.isSelected() ? 20 : 10;
            cost = unit * area;
        } catch (Exception e) {
        }
        list.add(new Row(list.size() + 1, customerNameTextField.getText(), customerAddressTextField.getText(), type, area, cost));
        writeToSQL(customerNameTextField.getText(), customerAddressTextField.getText(), type, area, cost);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void orderListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderListButtonActionPerformed
        int index = 0;
        for (Row row : list) {
            orderListTable.setValueAt(row.id, index, 0);
            orderListTable.setValueAt(row.name, index, 1);
            orderListTable.setValueAt(row.address, index, 2);
            orderListTable.setValueAt(row.type, index, 3);
            orderListTable.setValueAt(row.area + " ft2", index, 4);
            orderListTable.setValueAt("$" + row.cost, index, 5);
            index++;
        }
    }//GEN-LAST:event_orderListButtonActionPerformed

    private void writeToSQL(String name, String address, String type, double area, double cost) {
        createTable();
        Connection conn = null;
        Statement stmt = null;
        try {
            //STEP 2: Register JDBC driver
            Class.forName("com.mysql.jdbc.Driver");

            //STEP 3: Open a connection
            conn = DriverManager.getConnection(DB_URL, USER, PASS);

            //STEP 4: Execute a query
            stmt = conn.createStatement();

            Random rand = new Random(System.currentTimeMillis());

            int id = rand.nextInt(1000000);

            String sql = "INSERT INTO logs (id, CustomerName, CustomerAddress, FlooringType, FloorArea, FloorCost) "
                    + "VALUES (?, ?, ?, ?, ?, ?)";

            stmt.executeUpdate(sql);

            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setInt(1, id);
            preparedStatement.setString(2, name);
            preparedStatement.setString(3, address);
            preparedStatement.setString(4, type);
            preparedStatement.setDouble(5, area);
            preparedStatement.setDouble(6, cost);
            preparedStatement.executeUpdate();
        } catch (SQLException se) {
            //Handle errors for JDBC
        } catch (Exception e) {
            //Handle errors for Class.forName
        } finally {
            //finally block used to close resources
            try {
                if (stmt != null) {
                    conn.close();
                }
            } catch (SQLException se) {
            }// do nothing
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException se) {
            }//end finally try
        }//end try

    }

    private void createTable() {
        Connection conn = null;
        Statement stmt = null;
        try {
            //STEP 2: Register JDBC driver
            Class.forName("com.mysql.jdbc.Driver");

            //STEP 3: Open a connection
            conn = DriverManager.getConnection(DB_URL, USER, PASS);

            //STEP 4: Execute a query
            stmt = conn.createStatement();

            String sql = "CREATE TABLE logs "
                    + "(id INTEGER not NULL, "
                    + " CustomerName VARCHAR(30), "
                    + " CustomerAddress VARCHAR(50), "
                    + " FlooringType VARCHAR(10), "
                    + " FloorArea DOUBLE, "
                    + " FloorCost DOUBLE, "
                    + " PRIMARY KEY ( id ))";

            stmt.executeUpdate(sql);
        } catch (SQLException se) {
            //Handle errors for JDBC
        } catch (Exception e) {
            //Handle errors for Class.forName
        } finally {
            //finally block used to close resources
            try {
                if (stmt != null) {
                    conn.close();
                }
            } catch (SQLException se) {
            }// do nothing
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException se) {
            }//end finally try
        }//end try
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlooringApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlooringApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlooringApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlooringApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlooringApplication().setVisible(true);
            }
        });
    }

    class Row {

        int id;
        String name;
        String address;
        String type;
        double area;
        double cost;

        public Row() {

        }

        public Row(int _id, String _name, String _address, String _type, double _area, double _cost) {
            id = _id;
            name = _name;
            address = _address;
            type = _type;
            area = _area;
            cost = _cost;
        }
    }

    // JDBC driver name and database URL
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/test";

    //  Database credentials
    static final String USER = "root";
    static final String PASS = "";

    static java.util.List<Row> list = new ArrayList<Row>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addreddLabel;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton calculateButton;
    private javax.swing.JPanel calculatePanel;
    private javax.swing.JRadioButton carpetRadioButton;
    private javax.swing.JTextField customerAddressTextField;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JLabel floorAreaLabel;
    private javax.swing.JTextField floorAreaTextField;
    private javax.swing.JLabel floorCostLabel;
    private javax.swing.JTextField floorCostTextField;
    private javax.swing.JLabel floorLengthLabel;
    private javax.swing.JTextField floorLengthTextField;
    private javax.swing.JLabel floorTypeLabel;
    private javax.swing.JLabel floorWidthLabel;
    private javax.swing.JTextField floorWidthTextField;
    private javax.swing.JPanel florringPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton orderListButton;
    private javax.swing.JTable orderListTable;
    private javax.swing.JButton submitButton;
    private javax.swing.JPanel summaryPanel;
    private javax.swing.JTextArea summaryTextArea;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JRadioButton woodRadioButton;
    // End of variables declaration//GEN-END:variables

}
